plugins { id 'com.android.application' }

android {
    namespace 'com.receiptmakerpro'
    compileSdk 35

    defaultConfig {
        applicationId 'com.receiptmakerpro'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
}
