import React,{useMemo,useState}from'react';import{LayoutDashboard,ReceiptText,Package,History,Settings,Plus,Minus,Trash2,Printer,Download,Search,Store,ChevronRight,TrendingUp,ShoppingBag,Wallet,Menu,X,Check,Edit3}from'lucide-react';

type Product={id:string;name:string;price:number;category:string};
type Item={id:string;name:string;price:number;qty:number};
type Sale={id:string;date:string;items:Item[];total:number;customer:string};
const seed:Product[]=[{id:'1',name:'Classic Burger',price:650,category:'Fast Food'},{id:'2',name:'Chicken Biryani',price:480,category:'Meals'},{id:'3',name:'French Fries',price:220,category:'Sides'},{id:'4',name:'Chicken Roll',price:320,category:'Fast Food'},{id:'5',name:'Fresh Lemonade',price:180,category:'Drinks'},{id:'6',name:'Mineral Water',price:80,category:'Drinks'}];
const money=(n:number)=>'Rs '+n.toLocaleString('en-PK');
const uid=()=>Math.random().toString(36).slice(2,9);

export function App(){
 const [tab,setTab]=useState('dashboard');const [products,setProducts]=useState<Product[]>(()=>JSON.parse(localStorage.getItem('rm_products')||'null')||seed);
 const [sales,setSales]=useState<Sale[]>(()=>JSON.parse(localStorage.getItem('rm_sales')||'[]'));const [cart,setCart]=useState<Item[]>([]);const [query,setQuery]=useState('');const [customer,setCustomer]=useState('Walk-in Customer');const [business,setBusiness]=useState(()=>JSON.parse(localStorage.getItem('rm_business')||'null')||{name:'My Business',phone:'+92 300 0000000',address:'Your business address'});
 const [menu,setMenu]=useState(false);const [editing,setEditing]=useState<Product|null>(null);
 const save=(p:Product[])=>{setProducts(p);localStorage.setItem('rm_products',JSON.stringify(p))};
 const add=(p:Product)=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});
 const subtotal=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.qty,0),[cart]);const tax=subtotal*.05;const total=subtotal+tax;
 const complete=()=>{if(!cart.length)return;const sale={id:uid(),date:new Date().toLocaleString(),items:cart,total,customer};const next=[sale,...sales];setSales(next);localStorage.setItem('rm_sales',JSON.stringify(next));setCart([]);setCustomer('Walk-in Customer');setTab('history')};
 const filtered=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())||p.category.toLowerCase().includes(query.toLowerCase()));
 const nav=[['dashboard','Overview',LayoutDashboard],['pos','New Sale',ReceiptText],['products','Products',Package],['history','History',History],['settings','Business',Settings]] as const;
 return <div className="app">
  <aside className={menu?'side open':'side'}><div className="brand"><div className="logo"><ReceiptText size={21}/></div><div><b>Receipt</b><span>Maker Pro</span></div><button className="close" onClick={()=>setMenu(false)}><X size={19}/></button></div>
   <nav>{nav.map(([id,label,Icon])=><button className={tab===id?'nav active':'nav'} onClick={()=>{setTab(id);setMenu(false)}} key={id}><Icon size={19}/><span>{label}</span>{id==='pos'&&cart.length>0&&<em>{cart.length}</em>}</button>)}</nav>
   <div className="upgrade"><div className="spark">✦</div><b>Premium workspace</b><p>Fast billing. Beautiful receipts. Zero clutter.</p><button onClick={()=>setTab('settings')}>Explore features <ChevronRight size={15}/></button></div>
   <div className="side-foot">Local-first • Your data stays on this device</div>
  </aside>
  <main><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><small>Good business starts with a great receipt.</small><h1>{tab==='dashboard'?'Overview':tab==='pos'?'New Sale':tab==='products'?'Products':tab==='history'?'Sales History':'Business Profile'}</h1></div><div className="head-actions"><span className="status"><i/> Offline ready</span><button className="avatar">{business.name.slice(0,1).toUpperCase()}</button></div></header>
  {tab==='dashboard'&&<Dashboard sales={sales} products={products} money={money} onNew={()=>setTab('pos')}/>}
  {tab==='pos'&&<POS products={filtered} query={query} setQuery={setQuery} add={add} cart={cart} setCart={setCart} subtotal={subtotal} tax={tax} total={total} customer={customer} setCustomer={setCustomer} complete={complete} business={business} money={money}/>}
  {tab==='products'&&<Products products={products} setProducts={save} editing={editing} setEditing={setEditing} money={money}/>}
  {tab==='history'&&<HistoryPage sales={sales} money={money} business={business}/>}
  {tab==='settings'&&<SettingsPage business={business} setBusiness={(b:any)=>{setBusiness(b);localStorage.setItem('rm_business',JSON.stringify(b))}}/>}
  </main></div>
}

function Dashboard({sales,products,money,onNew}:{sales:Sale[];products:Product[];money:(n:number)=>string;onNew:()=>void}){
 const revenue=sales.reduce((s,x)=>s+x.total,0);return <section className="page">
  <div className="hero"><div><span className="eyebrow">TODAY'S WORKSPACE</span><h2>Sell smarter, <i>look professional.</i></h2><p>Create polished receipts in seconds and keep every sale organized.</p><button className="primary" onClick={onNew}><Plus size={18}/> Create new receipt</button></div><div className="hero-card"><ReceiptText size={30}/><b>Ready to print</b><span>58mm · 80mm · PDF</span></div></div>
  <div className="stats"><Stat icon={TrendingUp} label="Total revenue" value={money(revenue)} sub={sales.length+' receipts'}/><Stat icon={ShoppingBag} label="Sales" value={String(sales.length)} sub="All time"/><Stat icon={Package} label="Products" value={String(products.length)} sub="In catalog"/><Stat icon={Wallet} label="Avg. ticket" value={money(sales.length?revenue/sales.length:0)} sub="Per receipt"/></div>
  <div className="section-title"><div><h3>Recent sales</h3><p>Your latest transactions at a glance.</p></div><button className="ghost" onClick={onNew}>New receipt <ChevronRight size={16}/></button></div>
  <div className="table-card">{sales.length?<table><thead><tr><th>Receipt</th><th>Customer</th><th>Date</th><th>Items</th><th>Total</th></tr></thead><tbody>{sales.slice(0,6).map(s=><tr key={s.id}><td><b>#{s.id.toUpperCase()}</b></td><td>{s.customer}</td><td>{s.date}</td><td>{s.items.reduce((a,i)=>a+i.qty,0)}</td><td><strong>{money(s.total)}</strong></td></tr>)}</tbody></table>:<Empty icon={ReceiptText} title="No sales yet" text="Create your first receipt to see your business activity here."/>}</div>
 </section>
}
function Stat({icon:Icon,label,value,sub}:any){return <div className="stat"><div className="stat-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function POS({products,query,setQuery,add,cart,setCart,subtotal,tax,total,customer,setCustomer,complete,business,money}:any){
 return <section className="pos page"><div className="catalog"><div className="search"><Search size={18}/><input placeholder="Search products..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="cat-head"><div><h3>Quick catalog</h3><p>Tap an item to add it to the receipt.</p></div><span>{products.length} items</span></div><div className="product-grid">{products.map((p:any)=><button className="product" key={p.id} onClick={()=>add(p)}><div className="product-art">{p.name.slice(0,1)}</div><div className="product-info"><b>{p.name}</b><span>{p.category}</span><strong>{money(p.price)}</strong></div><div className="add-dot"><Plus size={16}/></div></button>)}</div></div>
 <div className="receipt"><div className="receipt-top"><div><span>NEW RECEIPT</span><h3>#{new Date().getTime().toString().slice(-6)}</h3></div><button className="icon-btn" onClick={()=>setCart([])}><Trash2 size={17}/></button></div><div className="customer"><Store size={16}/><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/></div><div className="receipt-items">{cart.length?cart.map((i:any)=><div className="line" key={i.id}><div><b>{i.name}</b><small>{money(i.price)} each</small></div><div className="qty"><button onClick={()=>setCart((c:any)=>i.qty===1?c.filter((x:any)=>x.id!==i.id):c.map((x:any)=>x.id===i.id?{...x,qty:x.qty-1}:x))}><Minus size={13}/></button><b>{i.qty}</b><button onClick={()=>setCart((c:any)=>c.map((x:any)=>x.id===i.id?{...x,qty:x.qty+1}:x))}><Plus size={13}/></button></div></div>):<Empty icon={ReceiptText} title="Receipt is empty" text="Choose products from the catalog."/>}</div><div className="totals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Tax · 5%</span><b>{money(tax)}</b></div><div className="grand"><span>Total</span><strong>{money(total)}</strong></div></div><button className="primary checkout" disabled={!cart.length} onClick={complete}><Check size={18}/> Complete sale</button><div className="print-note"><Printer size={14}/> Print-ready for 58mm & 80mm thermal printers</div></div></section>
}
function Products({products,setProducts,editing,setEditing,money}:any){
 const [name,setName]=useState('');const [price,setPrice]=useState('');const [category,setCategory]=useState('General');const open=(p:any)=>{setEditing(p);setName(p.name);setPrice(String(p.price));setCategory(p.category)};const reset=()=>{setEditing(null);setName('');setPrice('');setCategory('General')};const save=()=>{if(!name||!price)return;const p={id:editing?.id||uid(),name,price:Number(price),category};setProducts(editing?products.map((x:any)=>x.id===p.id?p:x):[...products,p]);reset()};return <section className="page"><div className="section-title"><div><h3>Product catalog</h3><p>Keep your most-used items one tap away.</p></div><button className="primary" onClick={()=>{reset();document.getElementById('product-form')?.scrollIntoView({behavior:'smooth'})}}><Plus size={17}/> Add product</button></div><div className="content-grid"><div className="table-card">{products.map((p:any)=><div className="product-row" key={p.id}><div className="mini-art">{p.name.slice(0,1)}</div><div><b>{p.name}</b><small>{p.category}</small></div><strong>{money(p.price)}</strong><button className="icon-btn" onClick={()=>open(p)}><Edit3 size={16}/></button><button className="icon-btn danger" onClick={()=>setProducts(products.filter((x:any)=>x.id!==p.id))}><Trash2 size={16}/></button></div>)}</div><div className="form-card" id="product-form"><span className="eyebrow">{editing?'EDIT PRODUCT':'NEW PRODUCT'}</span><h3>{editing?'Update item':'Add to catalog'}</h3><label>Product name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Zinger Burger"/></label><label>Price<input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0"/></label><label>Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="General"/></label><button className="primary full" onClick={save}>{editing?'Save changes':'Add product'}</button>{editing&&<button className="ghost full" onClick={reset}>Cancel</button>}</div></div></section>
}
function HistoryPage({sales,money,business}:any){const print=(s:any)=>{const w=window.open('','_blank');if(!w)return;w.document.write('<html><head><title>Receipt #'+s.id+'</title><style>body{font-family:Arial;max-width:360px;margin:30px auto}h2{text-align:center}div{display:flex;justify-content:space-between;padding:6px 0}.total{font-size:20px;font-weight:bold;border-top:1px dashed #999;margin-top:10px}</style></head><body><h2>'+business.name+'</h2><p style="text-align:center">'+business.address+'<br>'+business.phone+'</p><hr>'+s.items.map((i:any)=>'<div><span>'+i.name+' × '+i.qty+'</span><b>'+money(i.price*i.qty)+'</b></div>').join('')+'<div class="total"><span>Total</span><b>'+money(s.total)+'</b></div><p style="text-align:center">Thank you for your business.</p></body></html>');w.document.close();w.print()};return <section className="page"><div className="section-title"><div><h3>Sales history</h3><p>Every completed receipt, saved locally.</p></div><span className="count-pill">{sales.length} receipts</span></div><div className="table-card">{sales.length?<table><thead><tr><th>Receipt</th><th>Customer</th><th>Date</th><th>Total</th><th></th></tr></thead><tbody>{sales.map((s:any)=><tr key={s.id}><td><b>#{s.id.toUpperCase()}</b></td><td>{s.customer}</td><td>{s.date}</td><td><strong>{money(s.total)}</strong></td><td><button className="ghost small" onClick={()=>print(s)}><Printer size={14}/> Print</button></td></tr>)}</tbody></table>:<Empty icon={History} title="Your history is empty" text="Completed sales will appear here."/ >}</div></section>}
function SettingsPage({business,setBusiness}:any){const [b,setB]=useState(business);return <section className="page"><div className="settings-wrap"><div className="form-card wide"><span className="eyebrow">BUSINESS IDENTITY</span><h3>Make every receipt yours.</h3><p className="muted">These details appear on printed receipts and PDFs.</p><label>Business name<input value={b.name} onChange={e=>setB({...b,name:e.target.value})}/></label><label>Phone<input value={b.phone} onChange={e=>setB({...b,phone:e.target.value})}/></label><label>Address<textarea value={b.address} onChange={e=>setB({...b,address:e.target.value})}/></label><button className="primary" onClick={()=>setBusiness(b)}><Check size={17}/> Save profile</button></div><div className="feature-card"><div className="feature-icon">✦</div><h3>Built for busy counters.</h3><ul><li><Check/> Offline-first data storage</li><li><Check/> 58mm & 80mm receipt layouts</li><li><Check/> Instant print from history</li><li><Check/> Fast product catalog</li><li><Check/> Clean, ad-free workspace</li></ul></div></div></section>}
function Empty({icon:Icon,title,text}:any){return <div className="empty"><div><Icon size={22}/></div><b>{title}</b><p>{text}</p></div>}